version: '3.8'

services:
  database:
    image: bitnami/postgresql:13.3.0
    restart: always
    env_file: ".env"
    user: root
    volumes:
      - ./db_docker:/bitnami/postgresql
    ports:
      - "5454:5432"  # Remove this on production
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${DATABASE_PASSWORD}

  rust.axum.server:
    #    container_name: rust.axum.server
    build:
      context: ./rust.axum.server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./rust.axum.server/src:/app/src
    ports:
      - "8888:8888"

  python.fastapi.server:
    #    container_name: python.fastapi.server
    build: ./python.fastapi.server
    restart: always
    command: "sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'"
    volumes:
      - ./python.fastapi.server/app:/code
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      - database