version: '3.8'

services:
  rust.server:
    build:
      context: ./rust.server
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./rust.server/src:/app/src
    ports:
      - "8888:8888"

  fastapi_sample_server:
    container_name: fastapi_sample_server
    build: ./backend
    restart: always
    command: "sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'"
    volumes:
      - ./backend/app:/code
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file: ".env"
    depends_on:
      - database
  
  database:
    image: bitnami/postgresql:13.3.0
    restart: always
    container_name: database_sample
    env_file: ".env"
    user: root
    volumes:
      - ./db_docker:/bitnami/postgresql
    ports:
      - 5454:5432  # Remove this on production
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${DATABASE_PASSWORD}

  nginx:
    container_name: nginx_sample
    restart: unless-stopped
    logging:
      driver: none
    image: "nginx:latest"
    ports:
      - "80:8080"
    volumes:
      - ./static:/code/static
      - ./nginx-config-files/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-config-files/app.nginx.template:/etc/nginx/templates/app.nginx.template
      - "${EB_LOG_BASE_DIR:-./nginx-config-files}/nginx-proxy:/var/log/nginx"
